# -*- coding: utf-8 -*-
"""convert_to_tflite

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uEiVrWTfKPRKCDBwsK49UiFvWX6yOj-W
"""

import tensorflow as tf

model = tf.keras.models.load_model("final_model_adam.h5")
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open("model.tflite", "wb") as f:
    f.write(tflite_model)